#npm install
#npm test
#npm run buil
#firebase deploy 

#image: "ruby:2.5"
#image: rambabusaravanan/firebase
image: node:latest

stages:
  - deploy

cache:                  
  paths:                
    - node_modules/     
  key: "$CI_BUILD_REPO" 

deploy-prod:
  stage: deploy
  only:
    - master
  script:
    #- echo $FIREBASE_TOKEN 
    #- echo $FIREBASE_CONFIG_GITLAB 
    #- echo $TEST 
    - npm install -g firebase-tools
    - npm install -g bower
    - npm install
    - bower install --allow-root
    #- npm test
    - npm audit fix
    - npm install build
    - npm run build
    - firebase use AgabooDforce --token $FIREBASE_TOKEN
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN